### ISSUE TITLE
HyperSdkPlugin causing app launch delay in Android

### ISSUE THREAD

**Issue by hrajwade96** [juspay/hyper-sdk-flutter#13]
**Issue Description** : 
We are experiencing a significant delay in app launch times on Android, specifically related to the initialization of the HyperSdkPlugin. This issue is particularly evident on lower-end devices, where the initialization process takes approximately 2 seconds. During this time, the main thread is blocked, causing a delay in other launch processes.

**Expected Behavior** :
The app should launch without significant delay, and plugin initialization should not block the main thread for an extended period.

**Actual Behavior** :
The HyperSdkPlugin initialization during Flutter engine startup is causing a delay of around 2 seconds, noticeably affecting the app's launch performance.

**Additional Context** :
The plugin initialization is part of the automatic process handled by Flutter's GeneratedPluginRegistrant. Implementing lazy loading for this plugin could introduce additional overhead, as it would require custom initialization for all plugins. We are seeking an efficient solution that reduces app launch time without imposing significant changes to the plugin management process.

Reducing the app launch time is a top priority for us. Any assistance in resolving this issue would be greatly appreciated.

**Library version**: 
  
  hypersdkflutter: ^4.0.1

**Flutter doctor results** :

[✓] Flutter (Channel stable, 3.13.4, on macOS 14.0 23A344 darwin-arm64, locale en-IN)
    • Flutter version 3.13.4 on channel stable at /Users/hrishikeshrajwade/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (2 months ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/hrishikeshrajwade/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 73.0.4
    • Dart plugin version 231.8109.91

[✓] VS Code (version 1.71.2)
    • VS Code at /Users/hrishikeshrajwade/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

**Comment by hrajwade96** [comment]
@vimalkumar @boazjohn @murdore @dhinesh-juspay @balaganesh-juspay

**Comment by harshgarg18** [comment]
This issue is resolved on hypersdkflutter version `4.0.8`. Please re-open if you are still facing this issue.
