### ISSUE TITLE
I am unable to run the project

### ISSUE THREAD

**Issue by MeSunilFlutter** [juspay/hyper-sdk-flutter#26]
`
* What went wrong:
A problem occurred configuring project ':hypersdkflutter'.
> Failed to notify project evaluation listener.
   > Server returned HTTP response code: 403 for URL: https://public.releases.juspay.in/hyper-sdk/in/juspay/merchants/hyper.assets.payuzi/sdk_build_config.json?User-Agent=2.0.6&time=1714751767175&ip=192.168.1.3`

**Comment by harshgarg18** [comment]
Your clientId - `payuzi` is not configured on Juspay. Contact support@juspay.in or your KAM.
