### ISSUE TITLE
Failed to build iOS app - 'HyperSDK/VerifyHyperAssets.h' file not found

### ISSUE THREAD

**Issue by uvais-codes** [juspay/hyper-sdk-flutter#36]
While trying to run on ios simulator, it is failing and showing the below error.

```
Failed to build iOS app
Swift Compiler Error (Xcode): 'HyperSDK/VerifyHyperAssets.h' file not found
/Users/aaa/Documents/GitHub/shilpkar/build/ios/Debug-dev-iphonesimulator/XCFrameworkIntermediates/HyperSDK/HyperSDK.framework/Headers/Hyper.h:14:8
Hyper.h:14

Swift Compiler Error (Xcode): Could not build Objective-C module 'HyperSDK'
/Users/aaa/.pub-cache/hosted/pub.dev/hypersdkflutter-4.0.17/ios/Classes/SwiftHyperSdkFlutterPlugin.swift:9:7
SwiftHyperSdkFlutterPlugin.swift:9

Uncategorized (Xcode): Command CodeSign failed with a nonzero exit code
```

Kindly have a look to this issue

**Comment by Subhash703** [comment]
Hi @uvais-codes,

> HyperSDK/VerifyHyperAssets.h' file not found

This error is thrown intensionally by our SDK to avoid missing assets issue. Please make sure to do `pod install` before building the project. This will install the required assets.

Please follow the steps given [here](https://pub.dev/packages/hypersdkflutter#ios-setup) for IOS setup.

**Comment by uvais-codes** [comment]
We have already did `pod install` and it is finishing successfully. But this issue coming while building. @Subhash703

**Comment by Subhash703** [comment]
@uvais-codes Could you please confirm if you have added [post_install](https://pub.dev/packages/hypersdkflutter#ios-setup) script in your podfile.

```
post_install do |installer|
  fuse_path = "./Pods/HyperSDK/Fuse.rb"
  clean_assets = true
  if File.exist?(fuse_path)
    if system("ruby", fuse_path.to_s, clean_assets.to_s)
    end
  end
end
```

**Comment by uvais-codes** [comment]
Yes its worked. Thank you so much for your valuable support @Subhash703
